server:
  port: 9999
spring:
  application:
    name: consul-server
  cloud:
    consul:
      host: 192.168.58.128
      port: 8500
      discovery:
        instance-id: consul-server
        tags: server
        service-name: consul-server