server:
  port: 9004

spring:
  application:
    name: config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pandalin/springcloud
          username: pandalin
          password: linmin_123
          search-paths: config-repo
          default-label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
