server:
  port: 7001
spring:
  application:
    name: service-zipkin-first
  zipkin:
    base-url: http://localhost:7000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/