server:
  port: 9000

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pandalin/springcloud
          username:
          password:
          search-paths: config-repo
          default-label: master